# Setup
title:        A Personal Website
tagline:      A practice for creating a web page with GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       MMMMax
  url:        https://mmmmax-h.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
